routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Mail\Instagram;
use Illuminate\Support\Facades\Mail;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::Resource('/post','PostController');
Route::post('/comment','PostController@commentstore')->name('comment.store');
//Route::put('/post/status/{id}','PostController@status')->middleware(['web','auth'])->name('post.status');
Route::put('/post/status/{id}','PostController@status')->name('post.status');
Route::view('/countries/','posts.country')->name('post.country');
Route::get('/post/country/','PostController@showCountry')->name('post.countryid');
Route::get('/video/post','PostController@postVideo')->name('post.video');
Route::get('/image/post','PostController@postImage')->name('post.image');
Route::get('/country/post','PostController@countryindex')->name('country.index');
Route::get('/country/post/{id}','PostController@countryshow')->name('country.show');

//Route::get('/country/{country?}', 'CountryController@myCountryList')->name('country.list');
//Route::Resource('/country','CountryController');
Route::get('/like','PostController@likeordislike');
Route::get('/liked/{id}','PostController@likers')->name('likers');
Route::get('/disliked/{id}','PostController@dislikers')->name('dislikers');

//Route::Resource('/like','LikerController');
Route::get('/useredit','PostController@useredit')->name('user.edit');
Route::put('/userupdadte/{id}','PostController@userupdate')->name('user.update');
//
Route::get('/send-mail','PostController@postmail')->name('send-mail');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                        <a class='btn btn-primary' name='insert' href="{{route('post.index')}}">Goto Posts</a>
{{--                        <a class='btn btn-primary' name='country' href="{{route('country.index')}}">Country </a>--}}
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/messages.blade.php
@if ($errors->any())
    <div class="alert alert-danger  d-flex justify-content-center ">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
{{--dd($message);--}}
@if(Session::has('message'))
    <div class="Success alert-success d-flex justify-content-center">
        {{Session::get('message')}}
    </div>
@endif

resources/views/userupdate.blade.php
@extends('layouts.app')
@section('scripts')
    <script src="{{ asset('/assets/js/updateuser.js') }}" defer></script>
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Update User') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('user.update',[$user->id]) }}" id="userupdate" enctype="multipart/form-data">
                        @csrf
                        @method('put')
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>


                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $user->name }}" required autocomplete="name" autofocus>
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="profile_pic" class="col-md-4 col-form-label text-md-right">{{ __('profile_pic') }}</label>
                            <div class="col-md-6">
                                <img src="{{$user->profile_pic}}" width="100px" height="100px">
                                <input id="profile_pic" type="file" class="form-control @error('profile_pic') is-invalid @enderror" name="profile_pic" value="{{$user->profile_pic }}" required autocomplete="profile_pic" autofocus>
                                @error('profile_pic')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $user->email }}" required autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="Country" class="col-md-4 col-form-label text-md-right">{{ __('country') }}</label>
                            <div class="col-md-6">
                                <select class="form-control" id="country_id" name="country_id">
                                    @foreach(App\Country::all() as $country)
                                        <option value="{{$country->id}}"{{ $user->country_id == $country->id ? 'selected':''}}>{{$country->name}}</option>
                                    @endforeach
                                </select>
                                @error('profile_pic')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Register') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection