routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Mail\Instagram;
use Illuminate\Support\Facades\Mail;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::Resource('/post','PostController');
Route::post('/comment','PostController@commentstore')->name('comment.store');
//Route::put('/post/status/{id}','PostController@status')->middleware(['web','auth'])->name('post.status');
Route::put('/post/status/{id}','PostController@status')->name('post.status');
Route::view('/countries/','posts.country')->name('post.country');
Route::get('/post/country/','PostController@showCountry')->name('post.countryid');
Route::get('/video/post','PostController@postVideo')->name('post.video');
Route::get('/image/post','PostController@postImage')->name('post.image');
Route::get('/country/post','PostController@countryindex')->name('country.index');
Route::get('/country/post/{id}','PostController@countryshow')->name('country.show');

//Route::get('/country/{country?}', 'CountryController@myCountryList')->name('country.list');
//Route::Resource('/country','CountryController');
Route::get('/like','PostController@likeordislike');
Route::get('/liked/{id}','PostController@likers')->name('likers');
Route::get('/disliked/{id}','PostController@dislikers')->name('dislikers');

//Route::Resource('/like','LikerController');
Route::get('/useredit','PostController@useredit')->name('user.edit');
Route::put('/userupdadte/{id}','PostController@userupdate')->name('user.update');
//
Route::get('/send-mail','PostController@postmail')->name('send-mail');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Testing\MimeType;
use Illuminate\Support\Facades\Auth;
use const http\Client\Curl\AUTH_ANY;

class Post extends Model
{
    protected $fillable=[
        'post_type','url','description','user_id',
    ];
    public function getUrlAttribute($value){
        return url('/storage/'.$value);
}

public function comments(){
        return $this->hasMany(Comment::class);
}

    public function country(){
        return $this->hasOneThrough(Country::class,User::class);
}
    public function users(){
        return $this->belongsToMany(User::class,'posts__users','post_id','user_id');
    }
    public function user(){
        return $this->belongsTo(User::class);
    }
    public function likeusers(){
        return $this->users()->where('user_id',Auth::id());
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Country;
use App\Events\UserCreated;
use App\Jobs\MailChain;
use App\Jobs\SendEmail;
use App\Liker;
use App\Mail\Instagram;
use App\Mail\test;
use App\Mail\testdata;
use App\Post;
use App\Posts_Users;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Redis;

class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $post = Post::all();
//        $c=Comment::all();
//        $pu=Posts_Users::all();
        return view('posts.show_post', ['p' => $post]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create_post');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */

    private function mimeType($path)
    {
        return finfo_file(finfo_open(FILEINFO_MIME_TYPE), $path);
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'url' => 'required|mimes:jpeg,bmp,png,jpg,mp4,avi,mkv',
            'description' => 'required|max:1000',
        ]);
        $image = $request->file('url');
        $originalname = uniqid('Post_', 15) . '.' . $image->getClientOriginalExtension();
        $path = $image->storeAs('post', $originalname, 'public');
        $typeExtentension = $this->mimetype($request->url);
//        dd($typeExtentension);
        if (substr($typeExtentension, 0, 5) == 'image') {

            $typefile = 'image';
        } elseif (substr($typeExtentension, 0, 5) == 'video') {
            $typefile = 'video';
        }
        $post = Post::create([
            'url' => $path,
            'description' => $request->description,
            'user_id' => Auth::id(),
            'post_type' => $typefile,

            ]);
        return redirect()->route('post.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::all()->where('id', $id);
        $c = Comment::all();
        return view('posts.single_post', ['p' => $post]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
//    public function edit($id)
//    {
//        //
//    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
//    public function update(Request $request, $id)
//    {
//        //
//    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);
        $post->delete();
        return redirect()->route('post.index');
    }
    public function postVideo()
    {
        $post = Post::all()->where('post_type', 'video');
//        $comment = Comment::all();
        return view('posts.show_post', ['p' => $post]);
    }

    public function postimage()
    {
        $post = Post::all()->where('post_type', 'image');
//        $c=Comment::all();
//        return view('posts.show_post',['p'=>$post,'c'=>$c]);
        return view('posts.show_post', ['p' => $post]);
    }
    public function likers($id)
    {
        $post = Post::find($id);
        $user = Auth::id();
        $post->users()->attach($user);

//        return redirect()->route('post.index');
        return redirect()->back();
    }

    public function dislikers($id)
    {
        $post = Post::find($id);
        $user = Auth::id();
        $post->users()->detach($user);
//    return redirect()->route('post.index');
        return redirect()->back();
    }
    //country related functions
    public function countryindex()
    {
        $country = Country::all();
        return view('posts.country', ['country' => $country]);
    }
    public function countryshow($id)
    {
        $c = Country::with(['posts'])->find($id);
        return view('posts.show_post', ['p' => $c->posts]);
    }
//    user update and edit
    public function useredit(){
        $user=Auth::user();
        return view('userupdate',['user'=>$user]);
    }
    public function userupdate($id){
        $request=request();
        $image = $request->file('profile_pic');
        $originalname = $request->name . '-' . $request->id.'.jpg';
        $path = $image->storeAs('profile',$originalname,'public');

        $this->validate($request,[
            'name' =>['required'],
            'email' =>['required' ,'email'],
            'country_id' =>['required'],
        ]);
        $user =User::where('id',$id)->update([
            'name' => $request->name,
            'email' => $request->email,
            'profile_pic'=> $path,
            'country_id'=>$request->country_id,
        ]);



    }
//    Comments store
    public function commentstore(Request $request)
    {
//        $c= new Comment();
//        $c->user_id=Auth::id();
//        $c->post_id=$request->post_id;
//        $c->body=$request->cmnt;
//        $c->save();
        $commet=Comment::Create([
            'user_id'=>Auth::id(),
            'post_id'=>$request['post_id'],
            'body'=>$request['cmnt'],
        ]);
        event(new UserCreated($commet));
        return redirect()->route('post.index');

    }
    public function sendmail(){
        $user=User::find(1);

        Mail::to('one@example.com')->cc('one@example.com')->bcc('one@example.com')->send(new Instagram($user));
        view('mails.test');
        return 'Mail has been sent once ,to send it again refresh the page';
//        return redirect()->route('home');
    }
    public function postmail(Request $request){
//        try {
        $user=User::find(1);
////        $user=User::all();
//        dispatch(new SendEmail($user));
////        $when = now()->addSecond(10);
//        Mail::to($request->user())->send(new Instagram($user));
//        view('mails.test',['user'=>$user]);
//        $user=['email'=>'some@email.com'];
//        $emailjob=(new MailChain());
//        dispatch(function () use ($user){
//            $user->publish();
//        });
        $emailjob=(new MailChain());
//        dispatch($emailjob)->delay(Carbon::now()->addSeconds(5));
        dispatch($emailjob);
//
//        SendEmail::withChain([
//            new MailChain
//        ])->dispatch();
//        } catch (\Exception $e) {
//            Bugsnag::notifyException($e);
//
//            throw $e;
//        }
        return 'Mail has been sent once ,to send it again refresh the page';
//        return redirect()->route('home');
    }
//    public function enqueue(Request $request){
//        $user=['email'=>'some@email.com'];
//        $emailjob=(new SendEmail($user))->delay(Carbon::now())->addMinutes(5);
//        SendEmail::dispatch($emailjob)->delay(now()->addMinutes(10));
//    }
}

resources/views/posts/country.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Country wise Posts') }}</div>
                    <div class="card-body">
                        <div class="form-group d-flex justify-content-centre">
                            <div class="form-group row mx-2 mb-0">
                                <h3>Select the Country</h3>
                                <div class="dropdown justify-content-center">
                                    <button class="btn btn-secondary dropdown-toggle" type="button"
                                            id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
                                            aria-expanded="false">
                                        Country
                                    </button>
                                    <div class="dropdown-menu " aria-labelledby="dropdownMenuButton">
                                        @foreach($country as $c)
                                            <a class="dropdown-item" href="{{route('country.show',['id'=>$c->id])}}">{{$c->name}}</a>
                                        @endforeach
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/posts/create_post.blade.php
@extends('layouts.app')
@section('scripts')
    <script src="{{ asset('/assets/js/createpost.js') }}" defer></script>
@endsection
{{--@extends('messages')--}}
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Add Post') }}</div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('post.store') }}" enctype="multipart/form-data" id="createpost">
                            @csrf
                            <div class="form-group row">
                                <label for="url" class="col-md-4 col-form-label text-md-right">{{ __('url') }}</label>
                                <div class="col-md-6">
                                    <input id="url" type="file" class="form-control @error('url') is-invalid @enderror" name="url" value="{{ old('url') }}"  autocomplete="url" autofocus>
                                    @error('url')
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="url" class="col-md-4 col-form-label text-md-right">{{ __('Caption') }}</label>
                                <div class="col-md-6">
{{--                                    <textarea id="description" class="form-control" @error('description') is-invalid @enderror name="description" autocomplete="description" autofocus rows="3"></textarea>--}}
                                    <textarea type='text' id="description" class="form-control" @error('description') is-invalid @enderror name="description" >{{ old('description') }}</textarea>
                                    @error('description')
                                    <div class="alert alert-danger " role="alert invalid-feedback ">
                                            <strong>{{ $message }}</strong>
                                        </div>
{{--                                    {{dd($message)}}--}}
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <button class="btn btn-success" type="submit">Add Post</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/posts/show_post.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-mds">
                <div class="card col border-0">
                    <div class="card-header row"></div>
                    <div class="card-header row  ">
                        <a class='btn btn-primary mx-2' name='insert' href="{{route('post.create')}}">{{ __('Add Post') }}</a>
                        <div class="dropdown ">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Options
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class='nav-link' name='country' href="{{route('country.index')}}">Post Country wise </a>
                                <a class='nav-link' name='onlyvideo' href="{{route('post.video')}}">{{ __('Video Posts')}}</a>
                                <a class='nav-link' name='onlyimage' href="{{route('post.image')}}">{{ __('Image Posts')}}</a>
                            </div>
                        </div>
                    </div>
{{--                    <div class="card-header justify-content-around">--}}


                    <div class="card-body justify-content-around border-0">
                    @foreach($p as $post)
{{--                            {{dd($p)}}--}}
                            <div class="card border-0" style="width:600px">
                            <img class="card-img-top" src="{{$post->url}}" alt="Card image" style="width:100%">
                            <div class="card-header"><p class="card-text">{{$post->description}}</p></div>
                            <a href="{{route('post.show',[$post->id])}}" class="btn btn-primary">See Post</a>
                            <div class="card-body ">

                                @if(!(sizeof($post->likeusers)==null))
                                    <a class="btn btn-danger"
                                       href="{{route('dislikers', ['id' => $post->id])}}">Dislike</a>
                                @else
                                    <a class="btn btn-success"
                                       href="{{route('likers', ['id' => $post->id])}}">Like</a>
                                @endif
                                @if(Auth::id()==$post->user_id)
                                    <form action='{{route('post.destroy',[$post->id])}}' method="post">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-danger mx-2">Delete</button>
                                    </form>
                                @endif
                            </div>

                            <div class="card-header"></div>
                            <div class="card-content d-flex justify-content-center border-0">
                                <form action='{{route('comment.store')}}' class="form-inline" method="post">
                                    @csrf
                                    <input type="text" value="{{$post->id}}" name="post_id" hidden>
                                    <div class="col-sm-12 pb-2 py-2">
                                        <input id="cmnt" type="text" class="form-control @error('cmnt') is-invalid @enderror" name="cmnt" value="{{ old('cmnt') }}" required autocomplete="cmnt" autofocus>
                                        @error('cmnt')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                        <button type="submit" class="btn btn-success">Comment</button>
                                    </div>
                                </form>
                            </div>
                                <div class="card-content px-3 border-0">
                                    <p><strong>Comments:</strong></p>
                                    <div class="px-5">
                                        {{--                                    {{dd($cc->users->name)}}--}}
                                        <strong>{{$post->user->name}}:</strong>
                                        @foreach($post->comments as $cc)
                                            <span>{{$cc->body}}</span><br>
                                        @endforeach
                                    </div>
                                </div>
                        </div>
                        <br>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/posts/single_post.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-mds">
                <div class="card">
                    <div class="card-header"><a class='btn btn-primary' name='insert' href="{{route('post.create')}}">{{ __('Add Post') }}</a></div>
                    <div class="card-header justify-content-around"><a class='btn btn-primary' name='onlyvideo' href="{{route('post.video')}}">{{ __('Video Posts')}}</a>
                        <a class='btn btn-primary' name='onlyimage' href="{{route('post.image')}}">{{ __('Image Posts')}}</a></div>
                    <div class="card-body justify-content-around">
                        @foreach($p as $p)
                            {{--                            {{dd($p)}}--}}
                            <div class="card" style="width:400px">
                                <img class="card-img-top" src="{{$p->url}}" alt="Card image" style="width:100%">
                                <div class="card-header"><p class="card-text">{{$p->description}}</p></div>
                                <a href="{{route('post.index')}}" class="btn btn-primary">See all Posts</a>
                                <div class="card-body d-flex justify-content-center">

                                    @if($p->status==1)
                                        <form action='/post/status/{{$p->id}}' method="post">
                                            @csrf
                                            @method('put')
                                            <small class="text-primary">You Liked</small>
                                            <button type="submit" class="btn btn-success">Dislike</button>
                                        </form>
                                    @endif
                                    @if($p->status==0)
                                        <form action='/post/status/{{$p->id}}' method="post">
                                            @csrf
                                            @method('put')
                                            <button type="submit" class="btn btn-danger">Like</button>
                                        </form>
                                    @endif
                                    @if(Auth::id()==$p->user_id)

                                        <form action='/post/{{$p->id}}' method="post">
                                            @csrf
                                            @method('delete')
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    @endif


                                </div>
                                <div class="card-content px-3" >
                                    <p><strong>Comments:</strong></p>
                                    <div class="px-5">
                                        {{--                                    {{$p->id}}--}}
                                        {{--                                    {{\App\Country::all()->where('post_id',$p->id)}}--}}
                                        {{--                                    {{dd($p->id)}}--}}
                                        @foreach($c->where('post_id',$p->id) as $c)
                                            {{--                                        {{dd($c->where('post_id',$p->id))}}--}}
                                            {{--                                        @if($p->id==$c->post_id)--}}
                                            <p>{{$c->body}}</p>
                                            {{--                                        @endif--}}
                                        @endforeach
                                    </div>
                                </div>
                                <div class="card-header"></div>
                                <div class="card-content d-flex justify-content-center ">
                                    <form action='{{route('comment.store')}}' class="form-inline" method="post">
                                        @csrf
                                        <input type="text" value="{{$p->id}}" name="post_id" hidden>
                                        <div class="col-sm-12 pb-2 py-2">
                                            <input id="cmnt" type="text" class="form-control @error('cmnt') is-invalid @enderror" name="cmnt" value="{{ old('cmnt') }}" required autocomplete="cmnt" autofocus>
                                            @error('cmnt')
                                            <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                            @enderror
                                            <button type="submit" class="btn btn-success">Comment</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <br>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection